# Generated by Django 3.0.6 on 2020-08-25 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField()),
                ('request_date', models.DateTimeField()),
                ('type_message', models.CharField(choices=[('SMS', 'sms'), ('WTA', 'whatsapp'), ('PSH', 'push'), ('EML', 'e-mail')], max_length=3)),
                ('msg', models.TextField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
