# Generated by Django 3.0.6 on 2020-08-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200826_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendrequest',
            old_name='type_message',
            new_name='kind_message',
        ),
    ]
