# Generated by Django 3.0.6 on 2020-08-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200826_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='status',
            field=models.CharField(choices=[('SMS', 'sms'), ('WTA', 'whatsapp'), ('PSH', 'push'), ('EML', 'e-mail')], default='W', max_length=20),
        ),
    ]
