# Generated by Django 3.0.6 on 2020-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='status',
            field=models.CharField(choices=[('E', 'sented'), ('W', 'waiting')], default='W', max_length=20),
        ),
    ]
