# Generated by Django 3.0.6 on 2020-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200826_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='record_status',
            field=models.CharField(choices=[('A', 'actived'), ('D', 'deleted')], default='A', max_length=20),
        ),
    ]
